## jdbc datasource¡¨Ω”≈‰÷√ ####
jdbc.connection:
  driver_class: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.56.101:3306/sqltoy?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
  catalog: sqltoy
  username: sqltoy
  password: sqltoy
  
## sqltoy ≈‰÷√    #####
sqltoy:
  debug: true
  dialect: mysql
  batchSize: 200
  autoCommit: false
  showSql: true
  
## redis config ##
redis:
  maxActive: 2
  maxIdle: 1
  maxWait: 60000
  testOnBorrow: true
  host: 192.168.56.1
  port: 7001
  password: sagframe1235
  
#### es config ###########
elasticsearch:
  url:  http://192.168.56.101:9200
  username: elastic
  password: elastic123